### ISSUE TITLE
how to add more items or names?

### ISSUE THREAD

**Issue by madtomic** [amethyst-studio/ChestBlocker#5]
Looking at this template. I'm a bit confuse on what to do. Do I copy and paste for each item?

```
blocked-items:
  no-fancy-beef-allowed: #this can be anything to identify
    blocked-names:
     - "Royal Steak" # colorless names to block, can add as many as you want
    blocked-material: "COOKED_BEEF" # item without "minecraft:" before it, fully capitalized.
    use-names: true # use "blocked-names" otherwise, just material.
    block-message: "&cYou may not store {item} into this {container}." # formatted message with two placeholders.
```
