### ISSUE TITLE
feature: items.yml improvements

### ISSUE THREAD

**Issue by madtomic** [amethyst-studio/ChestBlocker#7]
Rather than adding one template per item. Can we do an array and add like items or materials as a group?
```
  no-fancy-food-allowed:
    blocked-names:
      - "Royal Beef"
      - "Fancy Fish"
    blocked-material:
      - "COOKED_BEEF"
      - "COOKED_FISH"
      - "COOKED_FISH:1"
    use-names: true
    block-message: "&cYou may not store {item} &cinto this {container}."
```

**Comment by xCykrix** [comment]
I will work on implementing this later today.

**Comment by madtomic** [comment]
A side note about fish. It uses fish:1, fish:2, etc for different fishes.

**Comment by xCykrix** [comment]
Good note, working on implementing a new system to handle items.yml which will build it dynamically and cache it on load and reload. Will help reduce tick load and make it slightly less taxing on thread.

**Comment by xCykrix** [comment]
f2b4c1b Implements Mechanics for Feature.

```yml
blocked-items:
  salmon-me-not: # this can be whatever, its just a unique list identifier
    blocked-names:
      - "Royal Steak" # base item name to block, plugin will attempt to strip out colorings (report any issues)
    blocked-materials:
      - "COOKED_FISH:1" # capitalized item name, without 'minecraft:' present.
    blocked-containers:
      - "CHEST" # capitalized InventoryType, available https://hub.spigotmc.org/javadocs/spigot/org/bukkit/event/inventory/InventoryType.html#enum.constant.summary
      - "ENDER_CHEST"
    use-names: true # should we use item names, or just materials?
    block-message: "&cYou may not store {item} into this {container}."
```
